### ISSUE TITLE
Error running with as filter

### ISSUE THREAD

**Issue by monje** [dmatveev/pandoc-yaml-vars#1]
Hi @dmatveev,

I've been doing some testing of the program as a pandoc filter and I'm getting an error. Do you know why?

<img width="704" alt="captura de pantalla 2016-03-03 a las 21 52 23" src="https://cloud.githubusercontent.com/assets/7488000/13492150/81a07772-e18a-11e5-91e9-18a3375141fd.png">

**Comment by dmatveev** [comment]
It is because parsing VARSFILE failed, as described in #2.

**Comment by dmatveev** [comment]
By the way, the proper invocation is `--filter=./pandoc-yaml-vars` - if the binary is in the current path and it is not in the `PATH`.

**Comment by monje** [comment]
Thanks @dmatveev!
