### ISSUE TITLE
YAML parsing issue.

### ISSUE THREAD

**Issue by monje** [dmatveev/pandoc-yaml-vars#2]
Hi @dmatveev,

I'm testing the program on its own, without using it as a pandoc filter and I'm getting a parsing error for the `VARSFILE` that we have used before. Here is the error:

<img width="605" alt="captura de pantalla 2016-03-03 a las 21 51 35" src="https://cloud.githubusercontent.com/assets/7488000/13492217/f12c3e46-e18a-11e5-9b70-e360ea4d4765.png">

Do you know what the issue is?

This may be causing #1, though I cannot be sure yet.

**Comment by dmatveev** [comment]
Hi Shawn,

Variable file parser only accepts strings like this:

```
variable-name : variable value
```

`---` and `...` are prohibited, but if you want, I can add support for that.

**Comment by dmatveev** [comment]
So, according to http://yaml-online-parser.appspot.com/, real YAML would accept both versions - with and without encloding `---`  / `...`. Will add it today

**Comment by monje** [comment]
Great work @dmatveev,

Thanks!

**Comment by dmatveev** [comment]
@monje Shawn, please check how it works now.
